# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install

    - name: Run test
      run: npm test
      
    - name: Rin eslint test
      run: npm lint

    - name: Notify Discord of success
      if: success()
      run: |
        curl -H "Content-Type: application/json" \
             -d "{\"username\": \"GitHub Actions\", \"content\": \"✅ Build succeeded for $GITHUB_REPOSITORY on $GITHUB_REF\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Notify Discord of failure
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
             -d "{\"username\": \"GitHub Actions\", \"content\": \"❌ Build failed for $GITHUB_REPOSITORY on $GITHUB_REF\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
